#!/bin/bash

############################################################
# Usage options
# -i : interactive -- calls a prompt to request information
#      Otherwise, will read from file "info"
# -n : don't parse args nor read input again ;
#      don't prefix every line with #

function main {

	parse=1
	for arg in "$@"; do
		if [ "$arg" == "-n" ] ; then
			parse=0
			break
		fi
	done

	if (( $parse )) ; then
		source "$(dirname "$0")/prompt"
		process_args "$@" 2> /dev/null
	fi
	
	first_line="$project_name"
	
	if [ -n "$repo_url" ] ; then
		first_line="$first_line <$repo_url>"
	fi
	
	license_url_parsed=""
	
	if [ -n "$license_url" ] ; then
		license_url_parsed="<$license_url>"
	fi
	
	year=$(date +%Y)
	
	short_header=$(cat << EOF
$first_line
(C) $author, $year <$author_email>
License $license $license_url_parsed
EOF
	)
	
	if (( $parse )) ; then
		sed -rn 's/^(.*)$/# \1/p' <<< $short_header
		echo ""
	else
		echo "$short_header"
	fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]] ; then
	main "$@"
fi
